data_folder: /home/xuewyang/Xuewen/Research/data/FACAD/jsons
model_folder: /home/xuewyang/Xuewen/Research/model/fashion/captioning/CNNC3
word_map_file: /home/xuewyang/Xuewen/Research/data/FACAD/jsons/WORDMAP_5.json
batch_size: 20
max_epochs: 30
num_layers: 4
learning_rate: 0.001